### ISSUE TITLE
Offer of maintaner help

### ISSUE THREAD

**Issue by lazzurs** [terraform-providers/terraform-provider-icinga2#40]
Hello @lrsmith 

Seems like this provider could do with some help, would be happy to help out being a maintainer if you are busy to get the issues and PRs cleaned up.

Same offer goes for the GO API as I would like to get this provider up to date with the full API. Happy to fork that and switch this provider over to the fork.

Thanks.

**Comment by lrsmith** [comment]
@lazzurs I am always happy to have more maintainers. I can add you fo the GO API. Hashicorp will need to add you for the terraform.

**Comment by lazzurs** [comment]
Sweet add me to the go API please and I will get work done. As for this and hashicorp who do I need to contact?

**Comment by attachmentgenie** [comment]
i would be willing to help out too, @lrsmith could you add me too?

**Comment by lrsmith** [comment]
I've added you both to the go-icinga2-api. It has been a while since i signed up to be a collaborator/maintainer for the icinga2 provider. I'll ask around in the meantime you can put PR against it. 

I'll follow-up outside this issue. 

Thanks for volunteering to help extend and maintain the API library and provider.
